version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      # - redis
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: taskomatic
      POSTGRES_PASSWORD: taskomatic
      POSTGRES_DB: taskomatic
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db_test:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskomatic_test
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
  # redis:
  #   image: redis:7
  #   restart: always
  #   ports:
  #     - "6379:6379"
volumes:
  postgres_data:
  postgres_test_data:
